### ISSUE TITLE
Pouvoir retirer le login par défaut (id + mdp)

### ISSUE THREAD

**Issue by AurelienBISOTTI** [progiseize/loginplus#2]
https://www.dolibarr.fr/forum/t/connexion-openid/43014/11

"J’ai quand même une question pour [@AurelienBisotti](https://www.dolibarr.fr/forum/u/aurelienbisotti), y a-t-il un moyen de désactiver la connexion par login + mot de passe pour forcer l’utilisation de l’OpenID ?"

**Comment by EchoLoGeek** [comment]
There is a hidden configuration that allows you to completely hide the form fields:
LOGINPLUS_HIDE_ALLFORM
